
export const data = {
	"Electronic Devices": {
		"Smart Phones": [
			"Realme",
			"Samsung",
			"Xiaomi",
			"OPPO",
			"Vivo",
			"Infinix",
			"Motorola",
			"Tecno",
			"Walton",
		],
		"Feature Phones": ["Walton", "Nokia", "Samsung", "iMAX", "5 Star", "Tinmo"],
		'Tablets': [],
		'Laptops': [
			"Laptops & Notebooks",
			"Gaming",
			"HP",
			"Asus",
			"Dell",
			"Lenovo",
			"Walton",
			"Acer",
			"MSI",
		],
		'Desktops': ["All-in-ONE", "Gaming"],
		"Gaming Consoles": [
			"PlayStations Consoles",
			"PlayStation Games",
			"PlayStations Controllers",
			"Nintendo Games",
			"Xbox Games",
			"Other Gaming Consoles",
		],
		'Cameras': [
			"DSLR",
			"Mirrorless",
			"Point & Shoot",
			"Bridge",
			"Car Cameras",
			"Action/Video Cameras",
		],
		"Security Cameras": [
			"IP Security Cameras",
			"IP Security Systems",
			"CCTV Security Cameras",
			"CCTV Security Systems",
		],
	},
	"Electronic Accessories": {
		"Mobile Accessories": [
			"Phone Cases",
			"Power Banks",
			"Cables & Converters",
			"Wall Chargers",
			"Wireless Chargers",
		],
		'Audio': [
			"Headphones & Headsets",
			"Home Entertainment",
			"Bluetooth Speaker",
			"Live Sound and Stage Equipments",
		],
		'Wearable': ["Smart Watches", "Virtual Reality"],
		"Console Accessories": [
			"PlayStation Controllers",
			"Other Gaming Accessories",
		],
		"Camera Accessories": [
			"Memory Cards",
			"DSLR Lens",
			"Mirrorless Lens",
			"Special Camera Lens",
			"TriPods & MonoPods",
			"Cases & Covers",
			"Lighting & Studio Equipments",
			"Dry Box",
			"Batteries",
		],
		"Computer Accessories": [
			"Monitors",
			"Mice",
			"PC Audio",
			"Keyboards",
			"Mice & Keyboards Combo",
			"Power Cords & Adaptors",
		],
		'Storage': [
			"External Hard Drives",
			"Internal Hadr Drives",
			"Flash Drives",
			"OTG drives",
		],
		'Printer': ["Printers", "Ink & Toners", "Printer Stands", "Fax MAchines"],
		"Computer Components": [
			"Graphics Cards",
			"Desktop Casings",
			"Motherboards",
			"Fans & Heatsinks",
			"RAM",
			"Processors",
		],
		"Network Components": [
			"Access Points",
			"Modems",
			"Network interface Cards",
			"Network Switches",
			"Routers",
			"Wireless USB Adapters",
		],
		'Software': [
			"Educational Media",
			"Operating Systems",
			"PC Games",
			"Security Softwares",
		],
	},
	"Home Appliances": {
		'Televisions': [
			"Smart",
			"LED",
			"OLED",
			"Walton",
			"Samsung",
			"Vision",
			"Sony",
			"Singer",
			"Others",
		],
		"Home Audio": [
			"SoundBars",
			"Home Entertainment",
			"Portable Players",
			"Live Sound and Stage Equipments",
		],
		"TV Accessories & Video Device": [
			"TV Receivers",
			"Projectors",
			"TV Remote Controllers",
			"Cables",
			"Wall Mounts & Projectors",
			"DVD Players",
		],
		"Large Appliances": [
			"Refrigerators",
			"Freezers",
			"Washing Machine",
			"Microwave Oven",
			"Electric Oven",
			"Hoods",
			"Cooktop & Range",
		],
		"Small Kitchen Appliances": [
			"Rice Cooker",
			"Blender, Mixer & Grinder",
			"Electric Kettle",
			"Juicer & Fruit Extraction",
			"Fryer",
			"Coffe Machine",
			"Pressure Cooker",
			"Sandwich Makers",
			"Toasters",
			"Specialty Cookware",
		],
		"Cooling & Heating": [
			"Air Conditioner",
			"Air Cooler",
			"Air Purifiers",
			"Dehumidifiers",
			"Water Heater",
		],
		'Fan': ["Ceiling", "Table", "Stand", "Mini", "Exhaust"],
		"Vacuums & Floor Care": [
			"Vacuum Cleaner",
			"Steam Mops",
			"Vacuum Cleaner Parts",
		],
		"Irons & Garment Steamers": ["Iron", "Sewing Machine"],
		"Water Purifiers & Filters": ["Pureit", "Kent", "Panasonic", "Eva Pure"],
	},
	"Health & Beauty": {
		"Bath & Body": [
			"Body & Massage Oils",
			"Body Moisturizers",
			"Body Scrubs",
			"Body Soaps & Shower Gels",
			"Foot Care",
			"Hair Removal",
			"Hand Care",
			"Sun Care",
			"Bath Accessories",
		],
		"Beauty Tools": [
			"Curling Irons & Wands",
			"Flat Irons",
			"Multi-stylers",
			"Hair Dryer",
			"Face Skin Care Tools",
			"Foot Relief Tools",
			"Hair Removal Accessories",
			"Slimming & Electric Massaging",
		],
		'Fragrances': ["Women", "Men", "Unisex"],
		"Hair Care": [
			"Shampoo",
			"Hair Treatments",
			"Hair Care Accessories",
			"Hair Brushes & Combs",
			"hair Coloring",
			"Hair Conditioner",
			"Wig & Hair Extensions & Pads",
		],
		'Makeup': [
			"Face",
			"Lips",
			"Eyes",
			"Nails",
			"Palettes & Sets",
			"Brushes & Sets",
			"Makeup Accessories",
			"Makeup Removers",
		],
		"Men's Care": [
			"Deodorants",
			"Hair Care",
			"Shaving & Grooming",
			"Skin Care",
		],
		"Personal Care": [
			"Deodorants",
			"Feminine Care",
			"Oral Care",
			"Parsonal Safety & Security",
		],
		"Skin Care": [
			"Moisturizers & Creams",
			"Serum & Essence",
			"Face Mask & Packs",
			"Face Scrubs & Exfoliators",
			"Facial Cleansers",
			"Lip Balm & Treatments",
			"Toner & Mists",
		],
		"Food Suppliments": [
			"Beauty Suppliments",
			"Multivitamins",
			"Sports Nutrition",
			"Well Being",
			"Sexual Health Vitamins",
		],
		"Medical Supplies": [
			"First Aid Supplies",
			"Health Accessories",
			"Health Monitors & Tests",
			"Nebulizers & Aspirators",
			"Ointments & Creams",
			"Scales & Body Fat Analyzers",
			"Wheelchair",
		],
		"Sexual Wellness": [],
	},
	"Babies & Toys": {
		"Mother & Baby": [],
		'Feeding': ["baby & Toddler Foods", "Milk Formula"],
		"Diapering & Potty": [
			"Cloth Diapers & Accessories",
			"Diaper Bags",
			"Wipes & Holders",
			"Disposable Diapers",
		],
		"Baby Gear": [
			"Baby Walkers",
			"Backpacks & Carriers",
			"Strollers",
			"Swings, Jumpers & Bouncers",
		],
		"Baby Personal Care": [
			"Baby Bath",
			"Bathing Tubs & Seats",
			"Shampoo & Conditioners",
			"Soaps, Cleansers, & Bodywash",
		],
		"Clothing & Accessories": [
			"Girls Clothing",
			"Girls Shoes",
			"Boys Clothing",
			"Maternity Waer",
			"New Born Unisex(0-6months)",
			"New Born Body Suits",
			"New Born Sets & Packs",
		],
		'Nursery': ["Bathroom Safety", "Mattresses & Bedding", "Sanitizers"],
		"Toys & Games": [
			"Action Figures & Collectibles",
			"Arts & Crafts for Kids",
			"Ball Prit & Accessories",
			"Block & Building Toys",
			"Doll & Accessories",
			"Dress Up & Pretend Play",
			"Electronic Toys",
			"Learing & Education",
			"Party Supplies",
			"Puzzles",
			"Slime & Squishy Toys",
			"Stuffed Toys",
		],
		"Baby & Toddler Toys": [
			"Activity Gym & Playmates",
			"Ball",
			"Bath Toys",
			"Crib Toys & Attachments",
			"Early Learing",
			"Indoor Climbers & Structures",
			"Push & Pull Toys",
			"Rocking & Spring Ride-Ons",
		],
		"Remote Control & Vehicles": [
			"Die-Cast Vehicles",
			"RC Vehicles & Batteries",
			"Play Trains & Railway Sets",
			"Play Vehicles",
			"Drones & Accessories",
		],
		"Sports & Outdoor Play": [
			"Fidget Spinners & Cubes",
			"Kids Bikes & Accessories",
			"Swimming Pool & Water Toys",
			"Outdoor Toys",
			"Play Tents & Tunnels",
			"Boxing",
			"Play Sets & Playground Equipments",
			"Sports Play",
			"Kids Tricycles",
			"Toys Sports",
		],
		"Traditional Games": ["Board Games", "Card Games", "Game Room Games"],
	},
	"Groceries & Pets": {
		'Beverages': ["Coffee", "Hot Chocolate Drinks", "Powdered Drink Mixes"],
		"Breakfast, Choco & Snacks": [
			"Biscuit",
			"Breakfast Cereals",
			"Chocolate",
			"Oatmeals",
		],
		"Food Staples": [
			"Canned Food",
			"Condiment Dressing",
			"Grains, Beans & Pulses",
		],
		"Cooking Ingredients": ["Oil", "Herbs & Spices", "Sauce"],
		"Laundry & Household": [
			"AirCare",
			"Cleaning",
			"Dishwashing",
			"Laundry",
			"Pest Control",
		],
		'Cat': ["Cat Food", "Grooming", "Toys & Accessories", "Litter & Toilet"],
		'Dog': [
			"Dog Food",
			"Dog Treats",
			"Grooming",
			"Toys & Accessories",
			"Carriers & Travel",
			"Leashes, Collars & Muzzles",
		],
		'Fish': ["Aquariums & Accessories", "Fish Food", "Starter Kits"],
		'Bird': ["Bird Food"],
		"Small Pets": ["Food & Accessories"],
		"Lifestyle Accessories": ["Lighters"],
	},
	"Home & Lifestyle": {
		'Bath': [
			"Bathroom Scales",
			"Shower Caddies & Hangers",
			"Shower Curtains",
			"Towel Rails & Warmers",
		],
		'Bedding': [
			"Blankets & Throws",
			"Comforters, Quilts & Duvets",
			"Mattress Pads",
			"Mattress Protectors",
			"Pillows & Bolsters",
		],
		'Decor': [
			"Artificial Flowers & Plants",
			"Candles & Candleholders",
			"Clocks",
			"Curtains",
			"Cushions & Covers",
			"Picture Frames",
			"Rugs & Carpets",
			"Vases & Vessels",
		],
		'Furniture': ["Bedroom", "Living Room", "home Office"],
		"Kitchen & Dining": [
			"Storage & Organization",
			"Coffee & Tea",
			"Cookware",
			"Dinnerware",
			"Kitchen & Table Linen",
			"Kitchen Storage & Accessories",
			"Kitchen Utensils",
			"Serveware",
		],
		'Lighting': [
			"Ceiling Lights",
			"Floor Lamps",
			"Lamp Shades",
			"Light Bulbs",
			"Lighting Fixtures & Component",
			"Outdoor Lighting",
			"Rechargeables & Flashlights",
			"Specialty Lighting",
			"Table Lamps",
			"Wall Lights & Sconces",
		],
		"Laundry & Cleaning": [
			"Brushes, Sponges & Wipers",
			"Brooms, Mops & Sweepers",
			"Laundry Baskets & Hampers",
			"Clothes Line & Drying Racks",
			"Ironing Boards",
		],
		"Tools, DIy & Outdoor": [
			"Outdoor",
			"Fixtures & Plumbing",
			"Electrical",
			"Hand Tools",
			"Power Tools",
			"Security",
		],
		"Stationery & Craft": [
			"Gifts & Wrapping",
			"Packaging & Cartoons",
			"Paper Products",
			"School & Office Equipment",
			"Writing & Correction",
			"Art Supplies",
			"Carft Supplies",
			"Sewing",
			"Religious Items",
		],
		"Media, Music & Books": [
			"eBooks",
			"Books",
			"Litareture Books",
			"Educational Books",
			"Religious Books",
			"Self Help & Meditation Books",
			"Musical Instruments",
			"Guitar",
			"guitar & Bass Accessories",
			"Keyboards & Piano",
			"Ukulele",
			"Drums & Percussion",
		]
	},
	"Women's Fashion": {
		"Sweater & Cardigans": [],
		"Women's Jackets & Coats": [],
		'Sarees': [],
		"Shalwar Kameez": [],
		"Unstitched Fabric": [],
		'Kurtis': [],
		"Girl's Fashion": [],
		"Women's Bags": [
			"Cross Body & Shoulder Bags",
			"Coin Purses & Pouches",
			"Top Handle Bags",
		],
		"Women's Shoes": ["Flat Sandals", "Heels", "Flat Shoes", "Wedges", "Flip Flop"],
		"Women's Accessories": [
			"Jewelleries",
			"Belts",
			"Hair Accessories",
			"Scarves",
			"Umbrellas",
		],
		"Lingerie, Sleep & Lounge": [
			"Bras",
			"Panties",
			"Lingerie Sets",
			"Sleep & Loungewear",
			"Tank Tops & Slips",
		],
		"Travel & Luggage": [
			"Weekender Bags",
			"Laptop Backpacks",
			"Suitcases",
			"Travel Accessories",
		]
	},
	"Men's Fashion": {
		"Men's Jackets & Coats": [
			"Bomber Jackets",
			"Denim Jackets",
			"Leather Jackets",
			"Rain Coats & Trenches",
		],
		"Hoodies & Sweatshirts": [],
		'Sweaters': [],
		"T-Shirts": [],
		'Shirts': [],
		"Polo Shirts": [],
		'Jeans': [],
		'Pant': ["Cargo", "Joggers & Sweatpants"],
		"Mens Bags": [
			"Backpack",
			"Suitcases",
			"Weekender Bags",
			"Business Bags",
			"Messenger Bags",
			"Crossbody Bags",
			"Travel Bags",
		],
		"Men's Shoes": [
			"Sneakers",
			"Sandals",
			"Formal Shoes",
			"Boots",
			"Flip Flops",
			"Slip-ons & Loafers",
			"House Slippers",
			"boys Shoes",
		],
		"Men's Accessories": [
			"Belt",
			"Wallet",
			"Hats & Caps",
			"Ties & Bow Ties",
			"Gloves",
			"Umbrellas",
		],
		'Clothing': ["Panjabi & Fatua", "Suits", "Underwear", "Boys Clothing"],
	},
	"Watches & Accessories": {
		"Men's Watch": ["Casual", "Business", "Fashion", "Sports"],
		"Men's Jewelleries": ["Rings", "Necklaces & Pendants", "Bracelets"],
		"Women's Watch": ["Casual", "Business", "Fashion"],
		"Women's Jewelleries": [
			"Rings",
			"Necklaces",
			"Pendants",
			"Earrings",
			"Jewellery Sets",
			"Bracelets",
		],
		"Fashion Mask": [],
		"Men's Belt": [],
		"Men's Wallet": [],
		'Sunglasses': ["Men", "Women", "Kids"],
		'Eyeglasses': ["Men", "Women", "Kids"],
		"Kid's Watch": [],
	},
	"Sports & Outdoor": {
		'Treadmills': [],
		"Fitness Accessories": [],
		"Dumb-bells": [],
		'Cycling': ["Bicycle", "Bicycle Accessories"],
		"Boxing, Martial Arts & MMA": [
			"Boxing Gloves",
			"Boxing Protective Gear",
			"Martial Art Equipment",
			"Punching Bags & Accessories",
		],
		"Men Shoes & Clothing": ["Clothing", "Shoes", "Accessories", "Bags"],
		"Outdoor Recreation": ["Golf", "Fishing", "Skateboards", "Water Sports"],
		"Exercise & Fitness": [
			"Exercise Bikes",
			"Elliptical trainers",
			"Strength Training Equipment",
		],
		"Racket Sports": ["Badminton", "Squash"],
		"Team Sports": ["Football", "Cricket", "Basket Ball", "Volleyball"],
		"Camping & Hiking": [
			"Tents",
			"Sleeping Bags",
			"Cooking Essentials",
			"Hiking Backpacks",
		],
		'Fanshop': [],
	},
	"Automotive & Motorbike": {
		'Automobile': ["Imported Cars", "Sedans", "SUVs", "Trucks"],
		"Auto Oils &Fluids": ["Additives", "Transmission Fluids"],
		"Interior Accessories": [
			"Seat Covers & Accessories",
			"Floor Mats & Cargo Liners",
			"Air Fresheners",
		],
		"Exterior Accessories": ["Covers"],
		"Exterior Vehicle Care": ["Car Polishes & Waxes"],
		"Interior Vehicle Care": ["Vacuums"],
		"Car Electronic Accessories": [],
		"Car Audio": ["Speakers"],
		'Motorcycle': ["Scooters", "Standard Bikes"],
		"Moto Parts & Accessories": [
			"Drivetrain & Transmission",
			"Oils & Fluids",
			"Tools & Maintenance",
		],
		"Motorcycle Riding Gear": ["Helmet", "Gloves", "Eyewear"],
	},
};
